feat: add paraswap wrapper
DecenterApps/defisaver-v3-contracts pull request #102
Opened 2021-11-29 10:17 UTC by majkic99

2021-11-30 12:54 UTC, nklipa13 requested changes
Ne mozemo da pakujemo u wrapperData, mora u offchainData.callData da se pakuje ako je to izvodivo

2021-11-30 12:54 UTC, nklipa13 commented on contracts/exchangeV3/offchainWrappersV3/ParaswapWrapper.sol
> +    /// @notice Takes order from Scp and returns bool indicating if it is successful
Remove SCP

2021-11-30 12:54 UTC, nklipa13 commented on contracts/exchangeV3/offchainWrappersV3/ParaswapWrapper.sol
> +        require(TokenUtils.ETH_ADDR.getBalance(address(this)) >= _exData.offchainData.protocolFee, ERR_PROTOCOL_FEE);
Ne znam jel ovo potrebno, mislim da ne postoji protocol fee koji mi placamo u etheru

2021-11-30 12:54 UTC, nklipa13 commented on contracts/exchangeV3/offchainWrappersV3/ParaswapWrapper.sol
> +        uint256 offset = abi.decode(_exData.wrapperData, (uint256));
Ovo se nismo razumeli, ovo ne moze da radi, jer wrapperData je zapravo onchain wrapper data, ja sam mislio da se u _exData.offchainData.callData radi pack (uint256, bytes), u ovom wrapperData ce npr da stoji path za UniV3 i onda ce da se pomesaju

2021-11-30 13:32 UTC, majkic99 commented on contracts/exchangeV3/offchainWrappersV3/ParaswapWrapper.sol
> +        require(TokenUtils.ETH_ADDR.getBalance(address(this)) >= _exData.offchainData.protocolFee, ERR_PROTOCOL_FEE);
Sklonjeno, paraswap nema takav protocol fee

2021-11-30 13:33 UTC, majkic99 commented on contracts/exchangeV3/offchainWrappersV3/ParaswapWrapper.sol
> +        uint256 offset = abi.decode(_exData.wrapperData, (uint256));
Done, pisem u Notionu nove info

2021-12-02 09:15 UTC, yippee-ki-yay approved these changes
lgtm

2021-12-02 09:18 UTC, nklipa13 approved these changes
lgtm

2021-12-06 09:46 UTC, merged