Feature/liquity actions
DecenterApps/defisaver-v3-contracts pull request #21
Opened 2021-05-17 09:14 UTC by kjaredic

2021-05-17 10:41 UTC, yippee-ki-yay commented on contracts/actions/liquity/helpers/LiquityHelper.sol
> +contract LiquityHelper {
This is a View contract not a helper contract

2021-05-17 10:42 UTC, yippee-ki-yay commented on contracts/actions/liquity/LiquitySupply.sol
> +        IBorrowerOperations(BorrowerOperationsAddr).addColl{value: _amount}(_upperHint, _lowerHint);
All DFS actions work only with tokens, no direct ETH sends. If the protocol accepts only ETH, unwrap weth and put int eth, but always assume actions work with weth

2021-05-17 10:43 UTC, yippee-ki-yay commented on contracts/actions/liquity/LiquityWithdraw.sol
> +        IBorrowerOperations(BorrowerOperationsAddr).withdrawColl(_amount, _upperHint, _lowerHint);
Should send back weth instead of eth, and a `_to` address needs to be an input

2021-05-17 10:43 UTC, yippee-ki-yay commented on contracts/actions/liquity/LiquitySupply.sol
> +        _amount = abi.decode(_callData[0], (uint256));
No from address?

2021-05-17 10:45 UTC, yippee-ki-yay commented on contracts/actions/liquity/LiquityPayback.sol
> +        (uint _LUSDAmount, address _upperHint, address _lowerHint) = parseInputs(_callData);
We don't write local variables with an '_' also always use camel case

2021-05-17 10:48 UTC, yippee-ki-yay commented on contracts/actions/liquity/LiquityOpen.sol
> +        _maxFeePercentage = _parseParamUint(_maxFeePercentage, _paramMapping[0], _subData, _returnValues);
_collAmount and _LUSDAmount should also be set in _parseParams

2021-05-17 10:49 UTC, yippee-ki-yay requested changes
Initial code review requires some changes, biggest error is not handling eth/weth conversions. Will do another review after tests and fixes.

2021-05-25 14:52 UTC, yippee-ki-yay commented
Merge with @majkic99 latest changes

2021-05-27 07:29 UTC, yippee-ki-yay commented on contracts/actions/liquity/LiquityBorrow.sol
> +        LUSDAmount = _parseParamUint(LUSDAmount, _paramMapping[1], _subData, _returnValues);
Always start variable names with lowber case if they are not constant LUSDAmount -> lusdAmount

2021-05-27 07:30 UTC, yippee-ki-yay commented on contracts/actions/liquity/LiquityBorrow.sol
> +    /// @notice Withdraw LUSD tokens from a trove: mint new LUSD tokens to the owner, and increase the trove's debt accordingly
Add natspec for input params as well (this applies to all the actions that have it missing)

2021-05-27 07:32 UTC, yippee-ki-yay commented on contracts/actions/liquity/LiquityBorrow.sol
> +        BorrowerOperations.withdrawLUSD(_maxFeePercentage, _LUSDAmount, _upperHint, _lowerHint);
Will this revert if it fails?

2021-05-27 07:33 UTC, yippee-ki-yay commented on contracts/actions/liquity/helpers/LiquityHelper.sol
> +    address constant public WETH_ADDR = 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2;
You have this in TokenUtils no need to duplicate

2021-05-27 07:37 UTC, yippee-ki-yay commented on contracts/actions/liquity/LiquityClose.sol
> +    using SafeMath for uint256;
Why the need for SafeMath?

2021-05-27 07:40 UTC, yippee-ki-yay commented on contracts/actions/liquity/LiquityOpen.sol
> +        return uint256(address(this));
Converting the address to uint doesn't make sense, also address(this) is DSProxy so redundant information. Return collAmount at that might change if it's uint.max

2021-05-27 07:43 UTC, yippee-ki-yay commented on contracts/actions/liquity/LiquitySupply.sol
> +    /// @notice Send ETH as collateral to a trove
Comment is not correct

2021-05-27 07:47 UTC, yippee-ki-yay commented on test/liquity/liquity-borrow.js
> +        const wrapEthAddr = await getAddrFromRegistry('WrapEth');
Use depositWeth() helper function

2021-05-27 07:51 UTC, yippee-ki-yay commented on test/utils-liquity.js
> +    const NICR = await liquityView['predictNICR(address,uint8,address,uint256,uint256)'](troveOwner, actionId, from, collAmount, LUSDamount);
Couldn't this be one call in a function that groups all 3 methods on the View contract?

2021-05-27 07:51 UTC, yippee-ki-yay commented on test/utils.js
> +const web3 = require('web3');
Sir pls no

2021-05-27 07:52 UTC, yippee-ki-yay requested changes
A lot of improvements since the last time, but there are still a few small issues that need to be fixed before merging. Also talk with @majkic99 about using his latest helper price method.

2021-05-28 12:13 UTC, kjaredic commented on contracts/actions/liquity/LiquityBorrow.sol
> +        BorrowerOperations.withdrawLUSD(_maxFeePercentage, _LUSDAmount, _upperHint, _lowerHint);
yes

2021-05-31 10:06 UTC, yippee-ki-yay commented on test/liquity/liquity-withdraw.js
> +const BNtoFloat = (bn) => hre.ethers.utils.formatUnits(bn, 18);
Move to utils.js

2021-06-02 14:00 UTC, yippee-ki-yay approved these changes
Lgtm!

2021-06-02 14:02 UTC, merged