Feature/hardhat flatten deploy verify tasks
DecenterApps/defisaver-v3-contracts pull request #46
Opened 2021-06-30 10:52 UTC by majkic99

2021-07-01 13:05 UTC, yippee-ki-yay commented on README.md
> +`npx hardhat customFlatten [file-path]` -  will flatten contract that is ready for deployment
And put it where?

2021-07-01 13:11 UTC, yippee-ki-yay commented on hardhat.config.js
> +task('fladepver', 'Deploys and verifies contract on etherscan')
This should be in separate file in script, not hardcoded in config

2021-07-01 13:12 UTC, yippee-ki-yay commented on scripts/hardhat-tasks-functions.js
> +    console.log(tx.data);
Link to etherscan

2021-07-01 13:16 UTC, yippee-ki-yay commented on scripts/hardhat-tasks-functions.js
> +    switch (network) {
`
let url = 'https://api.etherscan.io/api';

if (network !== 'mainnet') {
  url = `https://api-${network}.etherscan.io/api`;
}

`

2021-07-01 13:17 UTC, majkic99 commented on scripts/hardhat-tasks-functions.js
> +    switch (network) {
good thinking

2021-07-01 13:25 UTC, yippee-ki-yay commented on scripts/hardhat-tasks-functions.js
> +        gasPrice: hre.ethers.utils.parseUnits(gasPriceSelected, 'gwei'),
Sanity check for that number

2021-07-01 13:26 UTC, yippee-ki-yay commented on scripts/hardhat-tasks-functions.js
> +    const contract = await Contract.deploy(overrides);
Can we add a confirm yes/no prompt and info (what we are deploying, what network, how much it will cost)

2021-07-01 13:26 UTC, yippee-ki-yay requested changes
Script works but some small improvements needed

2021-07-02 07:29 UTC, yippee-ki-yay commented
The tools worked correctly on mainnet, after a few minor fixes. One last thing is to add an optional 'nonce' parameter so if the deployment tx gets stuck we can manually override it by using the same deployment nonce.

2021-07-02 11:29 UTC, majkic99 commented
Added optional nonce parameter for overriding stuck transactions

2021-07-02 11:36 UTC, yippee-ki-yay approved these changes

2021-07-02 11:37 UTC, merged