Feature/registry upgrade
DecenterApps/defisaver-v3-contracts pull request #55
Opened 2021-07-22 10:18 UTC by yippee-ki-yay

Add ability for users to change DSProxy owner in one tx and also keep a pool of premade dsproxies for easier on boarding.
The new DFSProxyRegistryController will be the owner of the DFSRegistry for this to work.

2021-07-22 11:26 UTC, majkic99 commented on contracts/actions/utils/ChangeProxyOwner.sol
> +    }
add Logger in action

2021-07-22 11:26 UTC, majkic99 commented on contracts/utils/DFSProxyRegistryController.sol
> +        emit NewProxy(msg.sender, newProxy);
maybe return newProxy address?

2021-07-22 11:33 UTC, majkic99 commented on contracts/utils/DFSProxyRegistryController.sol
> +        DFSProxyRegistry(DFS_PROXY_REGISTRY_ADDR).addAdditionalProxy(msg.sender, address(newProxy));
casting address -> address

2021-07-23 09:31 UTC, majkic99 commented on contracts/actions/utils/ChangeProxyOwner.sol
> +    // solhint-disable-next-line no-empty-blocks
// solhint-disable not needed

2021-07-23 09:46 UTC, majkic99 commented on contracts/utils/DFSProxyRegistryController.sol
> +    }
add view function that returns proxyPool.length

2021-07-23 09:49 UTC, majkic99 requested changes
looks safe, some small changes needed

2021-07-23 10:40 UTC, majkic99 approved these changes

2021-07-26 15:29 UTC, nklipa13 approved these changes
lgtm

2021-07-27 08:48 UTC, merged